RazorNews/Pages/CommentsManagment/Index.cshtml.cs
using Blazor.Business.Repository.IRepository;
using Blazor.Model.DTOs.Newses;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorNews.Pages.CommentsManagment
{
    [Authorize]
    public class IndexModel : PageModel
    {
        #region Constructor
        private readonly INewsRepository _newsRepository;
      
        [BindProperty]
        public IList<CommentDTO> Comments { get; set; }

        public IndexModel(INewsRepository newsRepository)
        {
            _newsRepository = newsRepository;
        }
        #endregion


        public async Task OnGetAsync()
        {
            Comments = (IList<CommentDTO>)await _newsRepository.GetAllCommentsByDate();
        }

        public async Task<IActionResult> OnPostUpdate(CommentDTO commentDto)
        {
            if (!ModelState.IsValid)
            {
                Comments = (IList<CommentDTO>)await _newsRepository.GetAllCommentsByDate();
                return Page();
            }

            await _newsRepository.UpdateComment(commentDto);
            return RedirectToPage();
        }
    }
}

RazorNews/Pages/CommentsManagment/Index.cshtml
@page
@model RazorNews.Pages.CommentsManagment.IndexModel
@{
    ViewData["Title"] = "Edit Comments";
}

<h2>Edit Comments</h2>

<table class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>@Html.DisplayNameFor(model => model.Comments[0].CreatedBy)</th>
            <th>@Html.DisplayNameFor(model => model.Comments[0].MailCreator)</th>
            <th>@Html.DisplayNameFor(model => model.Comments[0].DescriptionComment)</th>
            <th>@Html.DisplayNameFor(model => model.Comments[0].AnswerComment)</th>
            <th>@Html.DisplayNameFor(model => model.Comments[0].IsActive)</th>
            <th>عملیات</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var comment in Model.Comments)
        {
            <tr>
                <form method="post" asp-page-handler="Update">
                    <td><input asp-for="@comment.CreatedBy" class="form-control" /></td>
                    <td><input asp-for="@comment.MailCreator" class="form-control" /></td>
                    <td><input asp-for="@comment.DescriptionComment" class="form-control" /></td>
                    <td><input asp-for="@comment.AnswerComment" class="form-control" /></td>
                    <td>
                        <input type="checkbox" asp-for="@comment.IsActive" class="form-check-input" />
                        <label class="status-label @(comment.IsActive ? "active" : "inactive")"> @(comment.IsActive ? "فعال" : "غیرفعال")</label>
                    </td>
                    <td>
                        <input type="hidden" asp-for="@comment.CommentId" />
                        <button type="submit" class="btn btn-primary">ذخیره</button>
                    </td>
                </form>
            </tr>
        }
    </tbody>
</table>